version: '2.4'

services:
  api:
    build: .
    ports:
      - "3000:3000"             # web
      - "3001:7000"             # nREPL
    volumes:
      - ./psychic-pancake:/usr/src/app
      - ./m2:/root/.m2
      - ./ebay-data:/root/ebay-data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080
  react:
    build: "./frontend/psychic-pancake/"
    ports:
      - "3003:3000"
    volumes:
      - './frontend/psychic-pancake:/app'
    environment:
          - CHOKIDAR_USEPOLLING=true
          - PUBLIC_URL=web
          - REACT_APP_API_ROOT=${API_ROOT}
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/example.crt:/etc/nginx/example.crt'
      - './nginx/example.key:/etc/nginx/example.key'
              # - /star_xx_com.pem:/etc/nginx/cert/star_xx_com.pem
              # - /star_xx_com.key:/etc/nginx/cert/star_xx_com.key
              # - /star_xx_com.crt:/etc/nginx/cert/star_xx_com.crt
    ports:
      - 3323:3323
      - 3324:3324

# networks:
#   default:
#     driver: host
